Layout/EmptyLineAfterGuardClause:
  Exclude:
    - lib/web_package/signed_http_exchange.rb

Layout/SpaceInsideRangeLiteral:
  Exclude:
    - lib/web_package/cbor.rb

Layout/ExtraSpacing:
  Exclude:
    - lib/web_package/cbor.rb

Metrics/AbcSize:
  Max: 20
  Exclude:
    - lib/web_package/cbor.rb
    - lib/web_package/mice.rb
    - lib/web_package/signed_http_exchange.rb

Metrics/ClassLength:
  Exclude:
    - lib/web_package/signed_http_exchange.rb

Metrics/LineLength:
  Max: 100
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Exclude:
    - lib/web_package/cbor.rb
    - lib/web_package/mice.rb
    - lib/web_package/signed_http_exchange.rb

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - s

Style/ClassVars:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
